version: '3.7'
services:
    mysql:
        image: 'mysql:8.0'
        container_name: 'notes-app-mysql-db'
        working_dir: /application
        volumes:
            - '.:/application'
            - './notes-app-backend/mysql-disk:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=1234567
            - MYSQL_DATABASE=notes-db
            - MYSQL_USER=notes-db-user
            - MYSQL_PASSWORD=1234567
        ports:
            - '8083:3306'

    webserver:
        image: 'nginx:alpine'
        container_name: 'notes-app-webserver'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8081:80'

    php-fpm:
        build: phpdocker/php-fpm
        container_name: 'notes-app-php-fpm'
        working_dir: /application
        volumes:
            - './notes-app-backend:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
    appserver:
        image: 'notes-app-frontend'
        container_name: 'notes-app-http-server'
        # Build the image if don't exist
        build: './notes-app-frontend'
        ports:
            - 3000:81